In [4]:
import pandas as pd
import numpy as np
from functools import reduce
import ast
from pathlib import Path

In [5]:
metadata_df = pd.read_csv("../../data/processed/movies_metadata.csv")

In [6]:
display(metadata_df.head())
print()
display(metadata_df.info())

      id release_date    budget      revenue  runtime  popularity
0    862   1995-10-30  30000000  373554033.0     81.0   21.946943
1   8844   1995-12-15  65000000  262797249.0    104.0   17.015539
2  15602   1995-12-22         0          0.0    101.0   11.712900
3  31357   1995-12-22  16000000   81452156.0    127.0    3.859495
4  11862   1995-02-10         0   76578911.0    106.0    8.387519

<class 'pandas.DataFrame'>
RangeIndex: 45433 entries, 0 to 45432
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            45433 non-null  int64
 1   release_date  45346 non-null  str
 2   budget        45433 non-null  int64
 3   revenue       45430 non-null  float64
 4   runtime       43615 non-null  float64
 5   popularity    45430 non-null  float64
dtypes: float64(3), int64(2), str(1)
memory usage: 2.1 MB

None

### Missing: production data, credits data, keywords and text data

In [7]:
production_df = pd.read_csv("../../data/processed/nested_metadata.csv")
credits_df = pd.read_csv("../../data/processed/credits.csv")
keywords_df = pd.read_csv("../../data/processed/keywords_clean.csv")
text_df = pd.read_csv("../../data/processed/movie_text.csv")

In [8]:
print("Production data:")
print()
display(production_df.head())
display(production_df.info())
print()
print("Credits data:")
print()
display(credits_df.head())
display(credits_df.info())
print()
print("Keywords data:")
print()
display(keywords_df.head())
display(keywords_df.info())
print()
print("Text data:")
print()
display(text_df.head())
display(text_df.info())

Production data:

,id,original_title,release_date,genres,belongs_to_collection,production_companies,production_countries,spoken_languages
0,862,Toy Story,1995-10-30,Animation|Comedy|Family,Toy Story Collection,Pixar Animation Studios,United States of America,English
1,8844,Jumanji,1995-12-15,Adventure|Fantasy|Family,NaN,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,English|Français
2,15602,Grumpier Old Men,1995-12-22,Romance|Comedy,Grumpy Old Men Collection,Warner Bros.|Lancaster Gate,United States of America,English
3,31357,Waiting to Exhale,1995-12-22,Comedy|Drama|Romance,NaN,Twentieth Century Fox Film Corporation,United States of America,English
4,11862,Father of the Bride Part II,1995-02-10,Comedy,Father of the Bride Collection,Sandollar Productions|Touchstone Pictures,United States of America,English

<class 'pandas.DataFrame'>
RangeIndex: 45433 entries, 0 to 45432
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     45433 non-null  int64
 1   original_title         45433 non-null  str
 2   release_date           45346 non-null  str
 3   genres                 42991 non-null  str
 4   belongs_to_collection  4488 non-null   str
 5   production_companies   33562 non-null  str
 6   production_countries   39151 non-null  str
 7   spoken_languages       41478 non-null  str
dtypes: int64(1), str(7)
memory usage: 2.8 MB

None

Credits data:

,id,director,top_five_cast,cast_size,crew_size
0,862,John Lasseter,"[""Tom Hanks"", ""Tim Allen"", ""Don Rickles"", ""Jim...",13,106
1,8844,Joe Johnston,"[""Robin Williams"", ""Jonathan Hyde"", ""Kirsten D...",26,16
2,15602,Howard Deutch,"[""Walter Matthau"", ""Jack Lemmon"", ""Ann-Margret...",7,4
3,31357,Forest Whitaker,"[""Whitney Houston"", ""Angela Bassett"", ""Loretta...",10,10
4,11862,Charles Shyer,"[""Steve Martin"", ""Diane Keaton"", ""Martin Short...",12,7

<class 'pandas.DataFrame'>
RangeIndex: 45432 entries, 0 to 45431
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             45432 non-null  int64
 1   director       44545 non-null  str
 2   top_five_cast  45432 non-null  str
 3   cast_size      45432 non-null  int64
 4   crew_size      45432 non-null  int64
dtypes: int64(3), str(2)
memory usage: 1.7 MB

None

Keywords data:

      id                                keyword_names_clean
0    862  ['jealousy', 'toy', 'boy', 'friendship', 'frie...
1   8844  ['board game', 'disappearance', "based on chil...
2  15602  ['fishing', 'best friend', 'duringcreditssting...
3  31357  ['based on novel', 'interracial relationship',...
4  11862  ['baby', 'midlife crisis', 'confidence', 'agin...

<class 'pandas.DataFrame'>
RangeIndex: 31092 entries, 0 to 31091
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   31092 non-null  int64
 1   keyword_names_clean  31092 non-null  str
dtypes: int64(1), str(1)
memory usage: 485.9 KB

None

Text data:

,id,title,original_title,overview,original_language,status
0,2,Ariel,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,fi,Released
1,3,Shadows in Paradise,Varjoja paratiisissa,"An episode in the life of Nikander, a garbage ...",fi,Released
2,5,Four Rooms,Four Rooms,It's Ted the Bellhop's first night on the job....,en,Released
3,6,Judgment Night,Judgment Night,"While racing to a boxing match, Frank, Mike, J...",en,Released
4,11,Star Wars,Star Wars,Princess Leia is captured and held hostage by ...,en,Released

<class 'pandas.DataFrame'>
RangeIndex: 45433 entries, 0 to 45432
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 45433 non-null  int64
 1   title              45430 non-null  str
 2   original_title     45433 non-null  str
 3   overview           44329 non-null  str
 4   original_language  45422 non-null  str
 5   status             45349 non-null  str
dtypes: int64(1), str(5)
memory usage: 2.1 MB

None

### Columns to take from processed sets: `id`, `production_companies`, `production_countries`, `spoken_languages`, `director`, `top_cast`, `keywords`, `title`, `original_title`,  `original_title`, `original_language`, `overview`, `status`
### Additonal columns: `belongs_to_collection`

### New columns: `has_collection`, `company_count`, `country_count`, `spoken_language_count` | `cast_size`, `crew_size`, `has_director` | `keyword_count`, `title_word_count`, `overview_word_count`, `title_differs_from_original`

In [9]:
print(metadata_df['id'].duplicated().sum())
metadata_df.drop_duplicates(subset='id', inplace=True)
print(metadata_df['id'].duplicated().sum())

print(metadata_df['id'].isna().sum())
metadata_df.dropna(inplace=True)
print(metadata_df['id'].isna().sum())

print(metadata_df['id'].dtype)
metadata_df['id'] = metadata_df['id'].astype(int)
print(metadata_df['id'].dtype)

display(metadata_df['id'].info())

0
0
0
0
int64
int64
<class 'pandas.Series'>
Index: 43565 entries, 0 to 45432
Series name: id
Non-Null Count  Dtype
--------------  -----
43565 non-null  int64
dtypes: int64(1)
memory usage: 680.7 KB

None

In [10]:
data_frames = [production_df, credits_df, keywords_df, text_df]
combined_df = reduce(lambda  left,right: pd.merge(left,right,on=['id'], how='outer'), data_frames)
display(combined_df.head())
print()
display(combined_df.info())

,id,original_title_x,release_date,genres,belongs_to_collection,production_companies,production_countries,spoken_languages,director,top_five_cast,cast_size,crew_size,keyword_names_clean,title,original_title_y,overview,original_language,status
0,2,Ariel,1988-10-21,Drama|Crime,NaN,Villealfa Filmproduction Oy|Finnish Film Found...,Finland,suomi|Deutsch,Aki Kaurismäki,"[""Turo Pajala"", ""Susanna Haavisto"", ""Matti Pel...",4.0,6.0,"['underdog', 'prison', 'factory worker', 'pris...",Ariel,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,fi,Released
1,3,Varjoja paratiisissa,1986-10-16,Drama|Comedy,NaN,Villealfa Filmproduction Oy,Finland,English|suomi|svenska,Aki Kaurismäki,"[""Matti Pellonpää"", ""Kati Outinen"", ""Sakari Ku...",7.0,11.0,"['salesclerk', 'helsinki', 'garbage', 'indepen...",Shadows in Paradise,Varjoja paratiisissa,"An episode in the life of Nikander, a garbage ...",fi,Released
2,5,Four Rooms,1995-12-09,Crime|Comedy,NaN,Miramax Films|A Band Apart,United States of America,English,Allison Anders,"[""Tim Roth"", ""Antonio Banderas"", ""Jennifer Bea...",24.0,88.0,"['hotel', ""new year's eve"", 'witch', 'bet', 'h...",Four Rooms,Four Rooms,It's Ted the Bellhop's first night on the job....,en,Released
3,6,Judgment Night,1993-10-15,Action|Thriller|Crime,NaN,Universal Pictures|Largo Entertainment|JVC Ent...,Japan|United States of America,English,Stephen Hopkins,"[""Emilio Estevez"", ""Cuba Gooding Jr."", ""Denis ...",15.0,16.0,"['chicago', 'drug dealer', 'boxing match', 'es...",Judgment Night,Judgment Night,"While racing to a boxing match, Frank, Mike, J...",en,Released
4,11,Star Wars,1977-05-25,Adventure|Action|Science Fiction,Star Wars Collection,Lucasfilm|Twentieth Century Fox Film Corporation,United States of America,English,George Lucas,"[""Mark Hamill"", ""Harrison Ford"", ""Carrie Fishe...",106.0,20.0,"['android', 'galaxy', 'hermit', 'death star', ...",Star Wars,Star Wars,Princess Leia is captured and held hostage by ...,en,Released

<class 'pandas.DataFrame'>
RangeIndex: 45433 entries, 0 to 45432
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     45433 non-null  int64
 1   original_title_x       45433 non-null  str
 2   release_date           45346 non-null  str
 3   genres                 42991 non-null  str
 4   belongs_to_collection  4488 non-null   str
 5   production_companies   33562 non-null  str
 6   production_countries   39151 non-null  str
 7   spoken_languages       41478 non-null  str
 8   director               44545 non-null  str
 9   top_five_cast          45432 non-null  str
 10  cast_size              45432 non-null  float64
 11  crew_size              45432 non-null  float64
 12  keyword_names_clean    31092 non-null  str
 13  title                  45430 non-null  str
 14  original_title_y       45433 non-null  str
 15  overview               44329 non-null  str
 16  original_language      45422 non-null  str
 17  status                 45349 non-null  str
dtypes: float64(2), int64(1), str(15)
memory usage: 6.2 MB

None

In [11]:
combined_df.drop(columns=['original_title_x', 'release_date'], inplace=True)
combined_df.rename(columns={'original_title_y': 'original_title'}, inplace=True)
display(combined_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 45433 entries, 0 to 45432
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     45433 non-null  int64
 1   genres                 42991 non-null  str
 2   belongs_to_collection  4488 non-null   str
 3   production_companies   33562 non-null  str
 4   production_countries   39151 non-null  str
 5   spoken_languages       41478 non-null  str
 6   director               44545 non-null  str
 7   top_five_cast          45432 non-null  str
 8   cast_size              45432 non-null  float64
 9   crew_size              45432 non-null  float64
 10  keyword_names_clean    31092 non-null  str
 11  title                  45430 non-null  str
 12  original_title         45433 non-null  str
 13  overview               44329 non-null  str
 14  original_language      45422 non-null  str
 15  status                 45349 non-null  str
dtypes: float64(2), int64(1), str(13)
memory usage: 5.5 MB

None

In [12]:
final_df = combined_df.copy()

In [13]:
final_df['has_collection'] = combined_df['belongs_to_collection'].notna()
display(final_df[['belongs_to_collection', 'has_collection']])

      belongs_to_collection  has_collection
0                       NaN           False
1                       NaN           False
2                       NaN           False
3                       NaN           False
4      Star Wars Collection            True
...                     ...             ...
45428                   NaN           False
45429                   NaN           False
45430                   NaN           False
45431                   NaN           False
45432                   NaN           False

[45433 rows x 2 columns]

In [14]:
final_df['company_count'] = combined_df['production_companies'].str.split("|").str.len()
final_df['company_count'] = pd.to_numeric(final_df['company_count'], errors='coerce').fillna(0).astype(int)
display(final_df[['company_count', 'production_companies']])

       company_count                               production_companies
0                  2  Villealfa Filmproduction Oy|Finnish Film Found...
1                  1                        Villealfa Filmproduction Oy
2                  2                         Miramax Films|A Band Apart
3                  3  Universal Pictures|Largo Entertainment|JVC Ent...
4                  2   Lucasfilm|Twentieth Century Fox Film Corporation
...              ...                                                ...
45428              0                                                NaN
45429              0                                                NaN
45430              0                                                NaN
45431              1                               Elokuvayhtiö Oy Aamu
45432              4  Institut National de l'Audiovisuel (INA)|Radio...

[45433 rows x 2 columns]

In [15]:
final_df['country_count'] = combined_df['production_countries'].str.split("|").str.len()
final_df['country_count'] = pd.to_numeric(final_df['country_count'], errors='coerce').fillna(0).astype(int)
display(final_df[['country_count', 'production_countries']])

       country_count            production_countries
0                  1                         Finland
1                  1                         Finland
2                  1        United States of America
3                  2  Japan|United States of America
4                  1        United States of America
...              ...                             ...
45428              1                  United Kingdom
45429              1        United States of America
45430              1                         Finland
45431              1                         Finland
45432              2                 France|Portugal

[45433 rows x 2 columns]

In [16]:
final_df['spoken_languages_count'] = combined_df['spoken_languages'].str.split("|").str.len()
final_df['spoken_languages_count'] = pd.to_numeric(final_df['spoken_languages_count'], errors='coerce').fillna(0).astype(int)
display(final_df[['spoken_languages_count', 'spoken_languages']])

       spoken_languages_count       spoken_languages
0                           2          suomi|Deutsch
1                           3  English|suomi|svenska
2                           1                English
3                           1                English
4                           1                English
...                       ...                    ...
45428                       1                English
45429                       1                English
45430                       0                    NaN
45431                       1                  suomi
45432                       2     Português|Français

[45433 rows x 2 columns]

In [17]:
final_df['has_director'] = combined_df['director'].notna()
display(final_df[['has_director', 'director']])

       has_director          director
0              True    Aki Kaurismäki
1              True    Aki Kaurismäki
2              True    Allison Anders
3              True   Stephen Hopkins
4              True      George Lucas
...             ...               ...
45428          True       Molly Smith
45429          True      Sidney Lumet
45430          True      Jack Witikka
45431          True  Hannaleena Hauru
45432          True         Raúl Ruiz

[45433 rows x 2 columns]

In [18]:
final_df['keyword_count'] = combined_df['keyword_names_clean'].dropna().apply(lambda x: len(ast.literal_eval(x)))
final_df['keyword_count'] = pd.to_numeric(final_df['keyword_count'], errors='coerce').fillna(0).astype(int)
display(final_df[['keyword_count', 'keyword_names_clean']])

       keyword_count                                keyword_names_clean
0                  7  ['underdog', 'prison', 'factory worker', 'pris...
1                  4  ['salesclerk', 'helsinki', 'garbage', 'indepen...
2                 10  ['hotel', "new year's eve", 'witch', 'bet', 'h...
3                  5  ['chicago', 'drug dealer', 'boxing match', 'es...
4                 16  ['android', 'galaxy', 'hermit', 'death star', ...
...              ...                                                ...
45428              0                                                NaN
45429              0                                                NaN
45430              0                                                NaN
45431              3                      ['fantasy', 'youth', 'weird']
45432              0                                                NaN

[45433 rows x 2 columns]

In [19]:
final_df['title_word_count'] = combined_df['title'].str.split().str.len()
final_df['title_word_count'] = pd.to_numeric(final_df['title_word_count'], errors='coerce').fillna(0).astype(int)
display(final_df[['title_word_count', 'title']])

       title_word_count                             title
0                     1                             Ariel
1                     3               Shadows in Paradise
2                     2                        Four Rooms
3                     2                    Judgment Night
4                     2                         Star Wars
...                 ...                               ...
45428                 1                         Abduction
45429                 5       Tragedy in a Temporary Town
45430                 4          Silja - nuorena nukkunut
45431                 5  Thick Lashes of Lauri Mäntyvaara
45432                 6   Manuel on the Island of Wonders

[45433 rows x 2 columns]

In [20]:
final_df['overview_word_count'] = combined_df['overview'].str.split().str.len()
final_df['overview_word_count'] = pd.to_numeric(final_df['overview_word_count'], errors='coerce').fillna(0).astype(int)
display(final_df[['overview_word_count', 'overview']])

       overview_word_count                                           overview
0                       49  Taisto Kasurinen is a Finnish coal miner whose...
1                       21  An episode in the life of Nikander, a garbage ...
2                       38  It's Ted the Bellhop's first night on the job....
3                       69  While racing to a boxing match, Frank, Mike, J...
4                       52  Princess Leia is captured and held hostage by ...
...                    ...                                                ...
45428                   85  A horror comedy spoofing conspiracy theory mov...
45429                   70  Fifteen-year-old girl Dotty Fisher is assaulte...
45430                   87  In the 1910s, beautiful young Silja loses both...
45431                    0                                                NaN
45432                   18  Manuel is a young boy who travels from long ag...

[45433 rows x 2 columns]

In [21]:
final_df['title_differs_from_original'] = np.where(combined_df['title'] != combined_df['original_title'], True, False)
display(final_df[['title_differs_from_original', 'title', 'original_title']])

,title_differs_from_original,title,original_title
0,False,Ariel,Ariel
1,True,Shadows in Paradise,Varjoja paratiisissa
2,False,Four Rooms,Four Rooms
3,False,Judgment Night,Judgment Night
4,False,Star Wars,Star Wars
...,...,...,...
45428,False,Abduction,Abduction
45429,False,Tragedy in a Temporary Town,Tragedy in a Temporary Town
45430,False,Silja - nuorena nukkunut,Silja - nuorena nukkunut
45431,True,Thick Lashes of Lauri Mäntyvaara,Lauri Mäntyvaaran tuuheet ripset
45432,True,Manuel on the Island of Wonders,Manoel dans l'île des merveilles

In [22]:
all_genres = combined_df['genres'].dropna().str.split("|").explode().unique()
print(all_genres)

<StringArray>
[          'Drama',           'Crime',          'Comedy',          'Action',
        'Thriller',       'Adventure', 'Science Fiction',       'Animation',
          'Family',         'Romance',         'Mystery',           'Music',
          'Horror',         'Fantasy',     'Documentary',             'War',
         'Western',         'History',         'Foreign',        'TV Movie']
Length: 20, dtype: str

In [23]:
for genre in all_genres:
    final_df[genre] = combined_df['genres'].str.contains(genre).astype(int)

columns_to_print = ['genres'] + list(all_genres)
display(final_df[columns_to_print])

,genres,Drama,Crime,Comedy,Action,Thriller,Adventure,Science Fiction,Animation,Family,...,Mystery,Music,Horror,Fantasy,Documentary,War,Western,History,Foreign,TV Movie
0,Drama|Crime,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Drama|Comedy,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Crime|Comedy,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Action|Thriller|Crime,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Adventure|Action|Science Fiction,0,0,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45428,Fantasy|Drama,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
45429,Drama,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45430,Drama|Romance,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45431,Romance|Comedy,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45432,Fantasy|Drama,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [24]:
final_df.drop(columns=['genres'], inplace=True)
final_df.rename(columns={'keyword_names_clean': 'keywords', 'top_five_cast': 'top_cast'}, inplace=True)

In [25]:
#G

# Load the metadata again so we preserve rows with missing feature values
metadata_features_df = pd.read_csv(
    "../../data/processed/movies_metadata.csv"
)

# Prepare movie IDs for merging
metadata_features_df["id"] = pd.to_numeric(
    metadata_features_df["id"], errors="coerce"
)
metadata_features_df = metadata_features_df.dropna(subset=["id"])
metadata_features_df["id"] = metadata_features_df["id"].astype(int)
metadata_features_df = metadata_features_df.drop_duplicates(
    subset=["id"]
)

# Convert release_date to a date format
metadata_features_df["release_date"] = pd.to_datetime(
    metadata_features_df["release_date"], errors="coerce"
)

# Create the date features
metadata_features_df["release_year"] = (
    metadata_features_df["release_date"].dt.year
)
metadata_features_df["release_month"] = (
    metadata_features_df["release_date"].dt.month
)
metadata_features_df["release_decade"] = (
    metadata_features_df["release_year"] // 10 * 10
).astype("Int64")

# Convert numeric columns to numbers
for column in ["budget", "revenue", "runtime", "popularity"]:
    metadata_features_df[column] = pd.to_numeric(
        metadata_features_df[column], errors="coerce"
    )

# Create log features; treat negative values as invalid
metadata_features_df["log_budget"] = np.log1p(
    metadata_features_df["budget"].where(
        metadata_features_df["budget"] >= 0
    )
)
metadata_features_df["log_revenue"] = np.log1p(
    metadata_features_df["revenue"].where(
        metadata_features_df["revenue"] >= 0
    )
)
metadata_features_df["log_popularity"] = np.log1p(
    metadata_features_df["popularity"].where(
        metadata_features_df["popularity"] >= 0
    )
)

# Keep only the ID and the six features we need
feature_columns = [
    "id",
    "release_year",
    "release_month",
    "release_decade",
    "log_budget",
    "log_revenue",
    "runtime",
    "log_popularity",
]

metadata_features_df = metadata_features_df[feature_columns]

# Merge the features into the existing final dataset
final_df["id"] = pd.to_numeric(final_df["id"], errors="raise").astype(int)

final_df = final_df.merge(
    metadata_features_df,
    on="id",
    how="left",
    validate="one_to_one"
)

# Check the new columns and confirm row count
print("Final dataset shape:", final_df.shape)
print("Duplicate IDs:", final_df["id"].duplicated().sum())

display(final_df[feature_columns].head())

Final dataset shape: (45433, 51)
Duplicate IDs: 0

,id,release_year,release_month,release_decade,log_budget,log_revenue,runtime,log_popularity
0,2,1988.0,10.0,1980,0.000000,0.000000,69.0,1.581139
1,3,1986.0,10.0,1980,0.000000,0.000000,76.0,1.191529
2,5,1995.0,12.0,1990,15.201805,15.274126,98.0,2.305240
3,6,1993.0,10.0,1990,0.000000,16.311764,110.0,1.877734
4,11,1977.0,5.0,1970,16.213406,20.468887,121.0,3.764675

In [26]:
display(final_df.head())
print()
display(final_df.info())

,id,belongs_to_collection,production_companies,production_countries,spoken_languages,director,top_cast,cast_size,crew_size,keywords,...,History,Foreign,TV Movie,release_year,release_month,release_decade,log_budget,log_revenue,runtime,log_popularity
0,2,NaN,Villealfa Filmproduction Oy|Finnish Film Found...,Finland,suomi|Deutsch,Aki Kaurismäki,"[""Turo Pajala"", ""Susanna Haavisto"", ""Matti Pel...",4.0,6.0,"['underdog', 'prison', 'factory worker', 'pris...",...,0,0,0,1988.0,10.0,1980,0.000000,0.000000,69.0,1.581139
1,3,NaN,Villealfa Filmproduction Oy,Finland,English|suomi|svenska,Aki Kaurismäki,"[""Matti Pellonpää"", ""Kati Outinen"", ""Sakari Ku...",7.0,11.0,"['salesclerk', 'helsinki', 'garbage', 'indepen...",...,0,0,0,1986.0,10.0,1980,0.000000,0.000000,76.0,1.191529
2,5,NaN,Miramax Films|A Band Apart,United States of America,English,Allison Anders,"[""Tim Roth"", ""Antonio Banderas"", ""Jennifer Bea...",24.0,88.0,"['hotel', ""new year's eve"", 'witch', 'bet', 'h...",...,0,0,0,1995.0,12.0,1990,15.201805,15.274126,98.0,2.305240
3,6,NaN,Universal Pictures|Largo Entertainment|JVC Ent...,Japan|United States of America,English,Stephen Hopkins,"[""Emilio Estevez"", ""Cuba Gooding Jr."", ""Denis ...",15.0,16.0,"['chicago', 'drug dealer', 'boxing match', 'es...",...,0,0,0,1993.0,10.0,1990,0.000000,16.311764,110.0,1.877734
4,11,Star Wars Collection,Lucasfilm|Twentieth Century Fox Film Corporation,United States of America,English,George Lucas,"[""Mark Hamill"", ""Harrison Ford"", ""Carrie Fishe...",106.0,20.0,"['android', 'galaxy', 'hermit', 'death star', ...",...,0,0,0,1977.0,5.0,1970,16.213406,20.468887,121.0,3.764675

<class 'pandas.DataFrame'>
RangeIndex: 45433 entries, 0 to 45432
Data columns (total 51 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           45433 non-null  int64
 1   belongs_to_collection        4488 non-null   str
 2   production_companies         33562 non-null  str
 3   production_countries         39151 non-null  str
 4   spoken_languages             41478 non-null  str
 5   director                     44545 non-null  str
 6   top_cast                     45432 non-null  str
 7   cast_size                    45432 non-null  float64
 8   crew_size                    45432 non-null  float64
 9   keywords                     31092 non-null  str
 10  title                        45430 non-null  str
 11  original_title               45433 non-null  str
 12  overview                     44329 non-null  str
 13  original_language            45422 non-null  str
 14  status                       45349 non-null  str
 15  has_collection               45433 non-null  bool
 16  company_count                45433 non-null  int64
 17  country_count                45433 non-null  int64
 18  spoken_languages_count       45433 non-null  int64
 19  has_director                 45433 non-null  bool
 20  keyword_count                45433 non-null  int64
 21  title_word_count             45433 non-null  int64
 22  overview_word_count          45433 non-null  int64
 23  title_differs_from_original  45433 non-null  bool
 24  Drama                        45433 non-null  int64
 25  Crime                        45433 non-null  int64
 26  Comedy                       45433 non-null  int64
 27  Action                       45433 non-null  int64
 28  Thriller                     45433 non-null  int64
 29  Adventure                    45433 non-null  int64
 30  Science Fiction              45433 non-null  int64
 31  Animation                    45433 non-null  int64
 32  Family                       45433 non-null  int64
 33  Romance                      45433 non-null  int64
 34  Mystery                      45433 non-null  int64
 35  Music                        45433 non-null  int64
 36  Horror                       45433 non-null  int64
 37  Fantasy                      45433 non-null  int64
 38  Documentary                  45433 non-null  int64
 39  War                          45433 non-null  int64
 40  Western                      45433 non-null  int64
 41  History                      45433 non-null  int64
 42  Foreign                      45433 non-null  int64
 43  TV Movie                     45433 non-null  int64
 44  release_year                 45346 non-null  float64
 45  release_month                45346 non-null  float64
 46  release_decade               45346 non-null  Int64
 47  log_budget                   45433 non-null  float64
 48  log_revenue                  45430 non-null  float64
 49  runtime                      43615 non-null  float64
 50  log_popularity               45430 non-null  float64
dtypes: Int64(1), bool(3), float64(8), int64(27), str(12)
memory usage: 16.8 MB

None

In [27]:
Path("../../data/features").mkdir(parents=True, exist_ok=True)
final_df.to_csv("../../data/features/10_genre_features.csv", index=False)