In [217]:
import pandas as pd #imported panda library to use commands.
from pathlib import Path #import to make folders in the source code

In [218]:
project_root = Path.cwd().parents[1]

input_path = project_root / "data" / "processed" / "movies_metadata.csv"

df=pd.read_csv(input_path) #reading csv file.

#1 INSPECT FOLLOWING COLUMNS

- Loaded in files for DataFrame
- Created a list with the filtered columns.
- Made a copy of the filtered_columns

In [219]:


filtered_columns = ['title', 'original_title', 'overview' , 'original_language' , 'status', 'id'] #Since tagline had a bunch of NA values i removed the column as a whole.


clean_data = df[filtered_columns].copy() # makes a separate version of filtered data.

- Prints out the missing data from the six columns

In [220]:
missing_values = clean_data.isna().sum() #checks what's missing from each column.

print(missing_values) # prints missing data from each column.

title                  6
original_title         0
overview             954
original_language     11
status                87
id                     0
dtype: int64

#2 REMOVE UNNECESSARY WHITESPACE

- iterating through each filtered column to remove each string that has unnecessary white space from text value.

In [221]:
for column in filtered_columns:
    clean_data[column] = clean_data[column].str.strip() #.str treats each string value from the column as a string. 
                                                        # and strip remove unnecessary whitespace from every text value

#3 STANDARDIZING MISISNG AND PLACEHOLDER VALUES

In [222]:
clean_data.isna().sum()

title                  6
original_title         0
overview             954
original_language     11
status                87
id                     0
dtype: int64

In [223]:
clean_data = clean_data.fillna(pd.NA)

checking if all values are the set to NaN.

In [224]:
print(clean_data.loc[clean_data["overview"].isna(), "overview"])

32       NaN
300      NaN
634      NaN
635      NaN
641      NaN
        ...
45312    NaN
45347    NaN
45368    NaN
45369    NaN
45380    NaN
Name: overview, Length: 954, dtype: str

In [225]:
print(clean_data.loc[clean_data["title"].isna(), "title"])

19721    NaN
19722    NaN
29482    NaN
29483    NaN
35563    NaN
35564    NaN
Name: title, dtype: str

In [226]:
print(clean_data.loc[clean_data["overview"].isna(), "overview"])

32       NaN
300      NaN
634      NaN
635      NaN
641      NaN
        ...
45312    NaN
45347    NaN
45368    NaN
45369    NaN
45380    NaN
Name: overview, Length: 954, dtype: str

In [227]:
print(clean_data.isna().sum())

title                  6
original_title         0
overview             954
original_language     11
status                87
id                     0
dtype: int64

Majority of the values are already set to NaN so nothing to do with the placeholder value.

checking for repeated values in the six columns

In [228]:
for column in clean_data:
    duplicate_count = clean_data[column].duplicated().sum()
    print(f"Duplicates found in column {column}: {duplicate_count}")

Duplicates found in column title: 3158
Duplicates found in column original_title: 2063
Duplicates found in column overview: 1128
Duplicates found in column original_language: 45343
Duplicates found in column status: 45429
Duplicates found in column id: 0

In [229]:
print(clean_data['original_title'].duplicated().sum())

2063

- Parameters filter out the title, original_title, and id
- You see that there is duplicate id's in the dataframe generated below
- the keep false subset just shows EVERY duplicate

In [230]:
clean_data.loc[clean_data.duplicated(keep=False), ['title', 'original_title','id']] #first parameter looks for rows with duplicates, and second parameter i filtered two columns, and third it shows the duplicate row

Empty DataFrame
Columns: [title, original_title, id]
Index: []

- checking if the dupliate rows have all the same info and they do!

rows have changed since i deleted the duplicate rows..

In [231]:
clean_data.iloc[19925]

title                                                  Peppermint Soda
original_title                                          Diabolo menthe
overview             In the fall of 1963, Anne is becoming a teenag...
original_language                                                   fr
status                                                        Released
id                                                               80220
Name: 19925, dtype: str

In [232]:
clean_data.iloc[21854]

title                                                     Undocumented
original_title                                            Undocumented
overview             A documentary crew accompany a group of illega...
original_language                                                   en
status                                                        Released
id                                                               74008
Name: 21854, dtype: str

dropping all duplicates that have almost all the columns in common, only keeping the first copy and dropping the rest.

In [233]:
clean_data.drop_duplicates(subset = ['title', 'original_title' , 'overview','id','original_language', 'status'], keep = 'first', inplace = True, ignore_index = True )

checking for duplicates of title,original title, and id since they had something in common.

In [234]:
clean_data.loc[clean_data.duplicated(keep=False), ['title', 'original_title','id']] #checking for duplicates after removing them. it shows 0

Empty DataFrame
Columns: [title, original_title, id]
Index: []

below shows we have no more duplicates!

In [235]:
print(clean_data.duplicated().sum()) #checking for duplicates. marks 0

0